INSERT INTO produccion.Lugar(nombre_lugar) VALUES
('Parque Nacional Madidi'),
('Salar de Uyuni'),
('La Paz'),
('Copacabana'),
('Cochabamba'),
('Sucre'),
('Santa Cruz de la Sierra'),
('Potosí'),
('Oruro'),
('Tarija'),
('Villazón'),
('Tupiza'),
('Samaipata'),
('Valle de los Cintis'),
('Toro Toro'),
('Lago Titicaca'),
('Chiquitania'),
('El Alto'),
('Rurrenabaque'),
('Pampas del Yacuma'),
('Sierra de San Mateo'),
('Valle Grande'),
('San Ignacio de Velasco'),
('Isla del Sol'),
('Isla de la Luna'),
('Cholita Wrestling'),
('Camino de la Muerte'),
('San José de Chiquitos'),
('Parque Nacional Torotoro'),
('Monasterio de San Pedro'),
('La Cordillera Real'),
('Parque Nacional Noel Kempff Mercado'),
('Lago Poopó'),
('Reserva de Biosfera de las Yungas'),
('Reserva Nacional de Fauna Andina Eduardo Avaroa'),
('Pampa de la Sal'),
('San Pedro de Atacama'),
('Quebrada de Humahuaca'),
('Laguna Colorada'),
('Laguna Verde'),
('Loma de la Lluvia'),
('San Javier'),
('San Miguel de Velasco'),
('Los Volcanes de Lipez'),
('Pampa de Uyuni'),
('Aguas Termales de Baños de Morales'),
('Río Grande'),
('Chaco'),
('Los Andes'),
('Chancochoco'),
('Ruta de la Muerte'),
('Cataratas de las Mismas'),
('Caminos del Inca');