
INSERT INTO produccion.Actividad (nombre_actividad, descripcion_actividad) VALUES
('Senderismo', 'Actividad de caminar a través de rutas naturales, disfrutando de la flora y fauna local.'),
('Ciclismo de montaña', 'Recorrido en bicicleta por caminos de montaña o terrenos irregulares.'),
('Escalada en roca', 'Actividad de ascender formaciones rocosas utilizando técnicas de escalada.'),
('Rafting', 'Descenso de ríos en balsas inflables, enfrentando rápidos y aguas turbulentas.'),
('Parapente', 'Vuelo en parapente desde puntos elevados para disfrutar de vistas panorámicas.'),
('Pesca deportiva', 'Práctica de pesca con fines recreativos en ríos, lagos o mares.'),
('Observación de aves', 'Actividad de avistamiento y estudio de aves en su hábitat natural.'),
('Fotografía de naturaleza', 'Captura de imágenes de paisajes, fauna y flora en ambientes naturales.'),
('Esquí', 'Deporte de deslizamiento sobre nieve utilizando esquís.'),
('Snowboard', 'Deporte sobre nieve donde el practicante desciende montañas sobre una tabla.'),
('Visita a museos', 'Recorrido por museos para conocer la historia, arte y cultura local.'),
('Tour gastronómico', 'Recorrido para conocer y degustar la comida típica de una región o país.'),
('Visita a viñedos', 'Recorrido por viñedos para conocer el proceso de producción de vinos.'),
('Kayak en lago', 'Actividad acuática en la que se navega por un lago en una pequeña embarcación.'),
('Caminata nocturna', 'Senderismo durante la noche, para observar la fauna nocturna y las estrellas.'),
('Zumba', 'Ejercicio aeróbico en grupo al ritmo de música energética.'),
('Yoga al aire libre', 'Práctica de yoga en contacto directo con la naturaleza, en parques o espacios abiertos.'),
('Trekking', 'Caminar por largas distancias en áreas de montaña o naturaleza salvaje.'),
('Espeleología', 'Exploración de cavernas y sistemas subterráneos.'),
('Buceo', 'Actividad acuática en la que se explora el fondo marino con equipo especializado.'),
('Tour histórico', 'Recorrido por lugares de importancia histórica para aprender sobre el pasado de la región.'),
('Visita a mercados locales', 'Recorrido por mercados locales para conocer productos típicos y artesanías.'),
('Tour en globo aerostático', 'Vuelo en globo aerostático para disfrutar de vistas aéreas de paisajes naturales.'),
('Surf', 'Deporte acuático en el que se monta una tabla sobre las olas del mar.'),
('Ski acuático', 'Deporte en el que el practicante se desliza sobre el agua usando esquís.'),
('Caminata ecológica', 'Recorrido por senderos naturales con el objetivo de educar sobre la conservación del medio ambiente.'),
('Bicicross', 'Deporte que se practica en bicicletas en circuitos con saltos y obstáculos.'),
('Ciclismo urbano', 'Recorrido en bicicleta por la ciudad, explorando sus calles y puntos turísticos.'),
('Alpinismo', 'Escalada de montañas de gran altura, generalmente de nieve o hielo.'),
('Voluntariado ambiental', 'Participación en actividades que buscan la conservación de la naturaleza y el medio ambiente.');